
services:
    miniconda:
        image: continuumio/miniconda3
        volumes:
            - .:/app
        working_dir: /app
        command: /bin/bash
        tty: true
        # stdin_open: true

    anaconda:
        image: continuumio/anaconda3
        volumes:
            - .:/app
        working_dir: /app
        command: /bin/bash
        tty: true
